spring.application.name=p-integrador
spring.datasource.url=jdbc:mysql://localhost:3306/pintegrador
spring.datasource.username=omarmarg
spring.datasource.password=Pa$$w0rd

#create create-drop update validate
spring.jpa.hibernate.ddl-auto=update