spring.application.name=universalCopy
spring.datasource.url=jdbc:mysql://localhost:3306/universal_copy
spring.datasource.username=osva
spring.datasource.password=Pa$$w0rd

#create create-drop update validate
spring.jpa.hibernate.ddl-auto=update